services:
  - type: web
    name: hasura
    env: docker
    autoDeploy: false
    healthCheckPath: /healthz
    envVars:
      - key: HASURA_GRAPHQL_DATABASE_URL
        fromDatabase:
          name: hasura
          property: connectionString
      - key: HASURA_GRAPHQL_ENABLE_CONSOLE
        value: true
      - key: PORT
        value: 10000
      - key: HASURA_GRAPHQL_ADMIN_SECRET
        generateValue: true
      - key: HASURA_GRAPHQL_JWT_SECRET
        - type: HS256
        - key: 69a2cd79fcf74024aa1f9a9b3dacb404ff9888aec6bf44348378467311fbed74
databases:
  - name: hasura
