#####
# Documentation
# Redwood: https://render.com/docs/deploy-redwood
# YAML (all config values): https://render.com/docs/yaml-spec
#####

services:
  - name: redwoodjs-web
    type: web
    env: static
    buildCommand: yarn && yarn workspaces foreach run build && yarn rw deploy render web
    staticPublishPath: ./web/dist
    envVars:
      - key: NODE_VERSION
        value: 18
    routes:
      - type: rewrite
        source: /.redwood/functions/*
        destination: https://api.infinitykeys.io/*
      - type: rewrite
        source: /*
        destination: /index.html

  - name: redwoodjs-storybook
    type: web
    env: static
    buildCommand: yarn && yarn rw storybook --build
    staticPublishPath: ./web/storybook-static

  - name: redwoodjs-api
    type: web
    env: node
    region: oregon
    buildCommand: yarn && yarn build && yarn rw build api
    startCommand: yarn rw deploy render api
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: DATABASE_URL
        fromDatabase:
          name: redwoodjs-db
          property: connectionString

  - name: discord-dust-game-bot-mongodb
    type: pserv
    env: docker
    autoDeploy: false
    disk:
      name: data
      mountPath: /data/db
      sizeGB: 10

  - name: discord-dust-game-bot
    type: worker
    env: node
    region: oregon
    rootDir: packages/discord-dust-game-bot
    buildCommand: yarn && yarn build
    startCommand: node ./dist
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 18

  - name: function-stream
    type: web
    env: node
    region: oregon
    rootDir: packages/function-stream
    buildCommand: yarn && yarn build
    startCommand: yarn start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 18

databases:
  - name: redwoodjs-db
    region: oregon
    postgresMajorVersion: 15
